services:
  # backend:
  #   build:
  #     context: backend/
  #     dockerfile: Dockerfile.development
  #   restart: unless-stopped
  #   command: [ "tail", "-f", "/dev/null" ]
  #   environment:
  #     - SERVER_PORT=80
  #     - SERVER_ADDR=127.0.0.1
  #     - SURREALDB_HOST=db
  #     - SURREALDB_PORT=8000
  #     - SURREALDB_NAMESPACE=ns_template
  #     - SURREALDB_DBNAME=db_template
  #     - SURREALDB_USERNAME=root
  #     - SURREALDB_PASSWORD=root
  #     - RUST_LOG=debug
  #   volumes:
  #     - ./backend:/code:z
  #     - type: tmpfs
  #       target: /code/target
  db:
    image: surrealdb/surrealdb:v1.1.1
    restart: unless-stopped
    entrypoint: 
      - /surreal
      - start
      - --user
      - root
      - --pass
      - root
      - --log 
      - info
      - file:/data/surreal_dev.db
    ports:
      - 8000:8000
    volumes:
      - ./tmp:/data:rw
