@host = localhost
@port = 8080

###
POST http://{{host}}:{{port}}/api/login HTTP/1.1
content-type: application/json

{
    "username": "demo1",
    "password": "demo1"
}

###
POST http://{{host}}:{{port}}/api/logout HTTP/1.1
content-type: application/json

{
    "logout": true
}
