[env]
RUST_LOG="debug"
SURREALDB_HOST="127.0.0.1"
SURREALDB_PORT="8000"
SURREALDB_NAMESPACE="todo"
SURREALDB_DBNAME="todo"
SURREALDB_USERNAME="root"
SURREALDB_PASSWORD="root"
SERVICE_PWD_KEY="CKUGFOD9_2Qf6Pn3ZFRYgPYb8ht4vKqEG9PGMXTB7497bT0367DjoaD6ydFnEVaIRda0kKeBZVCT5Hb62m2sCA"
SERVICE_TOKEN_KEY=""
SERVICE_TOKEN_DURATION_SEC="1800" # 30 minites
SERVICE_WEB_FOLDER=""