[env]
RUST_LOG="debug"
SURREALDB_HOST="127.0.0.1"
SURREALDB_PORT="8000"
SURREALDB_NAMESPACE="todo"
SURREALDB_DBNAME="todo"
SURREALDB_USERNAME="root"
SURREALDB_PASSWORD="root"
SERVICE_PWD_KEY=""
SERVICE_TOKEN_KEY=""
SERVICE_TOKEN_DURATION_SEC="1800" # 30 minites
SERVICE_WEB_FOLDER=""