USE DbTemplate;
IF OBJECT_ID(N'dbo.Task', N'U') IS NULL
CREATE TABLE dbo.Task
(
    TaskID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY CLUSTERED DEFAULT NEWID(),
    Title VARCHAR(250) NOT NULL,
    Done BIT NOT NULL DEFAULT 'false',
    CreateBy UNIQUEIDENTIFIER FOREIGN KEY REFERENCES dbo.UserInfo(UserInfoID),
    CreateOn DATETIME2,
    UpdateBy UNIQUEIDENTIFIER FOREIGN KEY REFERENCES dbo.UserInfo(UserInfoID),
    UpdateOn DATETIME2,
    Deleted CHAR(1) NOT NULL CHECK (Deleted = 'Y' OR Deleted = 'N'),
    DeleteOn DATETIME2,
    DeleteBy UNIQUEIDENTIFIER FOREIGN KEY REFERENCES dbo.UserInfo(UserInfoID)
);