USE DbTemplate;

IF OBJECT_ID(N'dbo.UserInfo', N'U') IS NULL
CREATE TABLE dbo.UserInfo
(
    ID INT IDENTITY NOT NULL PRIMARY KEY CLUSTERED,
    -- UUID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY CLUSTERED,
    Username VARCHAR(50) NOT NULL UNIQUE NONCLUSTERED,
    Name NVARCHAR(250),
    Email VARCHAR(50) NOT NULL UNIQUE NONCLUSTERED,
    EmailVerified DATETIME2,
    Password VARCHAR(200),
    PasswordSalt VARCHAR(200),
    TokenSalt VARCHAR(200),
    Role VARCHAR(5),
    CreateBy VARCHAR(50),
    CreateOn DATETIME2,
    UpdateBy VARCHAR(50),
    UpdateOn DATETIME2
);