USE NS ns_template;
USE DB db_template;
CREATE task:Ay5RJ87J5dSkChl9KlSD CONTENT {
    title: 'task demo1',
    create_by: user_info:iR1f8i7Wg7jipR3uhDhJ,
    update_by: user_info:iR1f8i7Wg7jipR3uhDhJ,
};
CREATE task CONTENT {
    title: 'task demo2',
    create_by: user_info:iR1f8i7Wg7jipR3uhDhJ,
    update_by: user_info:iR1f8i7Wg7jipR3uhDhJ,
};
CREATE task CONTENT {
    title: 'task demo3',
    create_by: user_info:iR1f8i7Wg7jipR3uhDhJ,
    update_by: user_info:iR1f8i7Wg7jipR3uhDhJ,
};